[instance]
problem_instance = "/fajsp/dafjs/DAFJS01"

[algorithm]
population_size = 100   # number of individuals in the population
ngen = 100000           # number of generations
seed = 42               # random seed
indpb = 0.1             # probability of mutating each gene
cr = 0.7                # probability of mating
multiprocessing = false # use multiprocessing for parallel evaluation of individuals (default uses all threads)
time_limit = 1800       # wall-clock time limit in seconds

[output]
logbook = true          # display logbook during search
show_precedences = true # draw precedence relations graph of the problem instance
show_gantt = true       # draw ganttchart of found solution
save_gantt = true       # save ganttchart to file
save_results = true     # save results to file
exp_name = ""           # name of the experiment, used for saving results.
                        # If empty (""), the name of the problem instance is used
folder = ""             # folder to save results, used for saving results.
                        # If empty (""), the results are saved to the current working directory.

